### PR TITLE
Re #409: fix RAM performance in reading nrrd

### PR DESCRIPTION
**Pull request by Punzo**

### CODE REVIEW

**Comment by pieper** [comment]
Hi @Punzo - thanks for working on this - but can you elaborate on what problem this addresses and how this improves things?  Is there any way to test it?

To be honest I'm not a fan of messing around with the nrrd library because it is pretty central to so many uses in slicer and generally has worked well.

Also, would you consider contributing this to the upstream nrrd library instead?  The fewer custom edits in our fork the better.  Gordon would probably be able to look at this and understand quickly what issue it addresses and whether it has a potential to break other things.

**Comment by Punzo** [comment]
Hi @Steve sorry I meant to do the PR elsewhere for internal review and after that pushing it here.

Anyway the idea is that the reading can be done in chunks and so streaming it (avoid the usage of x2 memory in the Slicer vtkTeemNRRDReader, when loading a nrrd file. This can be an issue when the file is several giga large). Anyway, I have still to finish this (I have to do the same for the writing) and then I'll reopen all the PRs (here and Slicer branch). 

P.S.: could you give me actually the link where the teem code is hosted? I mean is hosted here: **https://svn.code.sf.net/p/teem/code/teem/trunk** ; but I am not sure how to directly contribute to svn repo and I didn't find any document how to contribute. 
P.S.2: the modifications are kept at minimum and I have already tested that it will work with several nrrd data. But, yes I agree it will be necessary to test this pretty close to be sure to not breaking things.

**Comment by pieper** [comment]
Thanks Davide!

I'll email Gordon and see if we can clarify how he wants to handle this going forward.  I know he's still interested in teem, but also he's a busy professor now.

**Comment by Punzo** [comment]
ok thanks Steve!

**Comment by dzenanz** [comment]
Streaming support for NRRD would be quite welcome [in ITK](https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/ThirdParty/NrrdIO/src/NrrdIO) too!

**Comment by lassoan** [comment]
How nrrdio library in ITK is related to teem library? Who maintains them and how actively developed/maintained are they?

**Comment by pieper** [comment]
I wrote Gordon Kindlmann, the original teem author, yesterday to find out his preferences.  If he's no longer able to maintain teem we should designate an 'upstream' master repository to use in Slicer and ITK.

**Comment by jcfr** [comment]
This thread should give more context: https://discourse.itk.org/t/add-a-parallel-compression-method-to-nrrd-and-or-metaimage/696/16

**Comment by pieper** [comment]
Yes, I suspect he will appreciate it if we put in some effort to set up a repository, CI testing, etc.  Keeping him in the loop of course.  Let's see what he says.  It doesn't look like he's got a github presence currently.

**Comment by hjmjohnson** [comment]
Many thumbs up for getting TEEM onto github.  The ITK (and Slicer/VTK/NAMIC) communities have a good track record for assisting with maintenance of important tools if there is a clear path to review and acceptance.

If TEEM were on github, and there were empowered repository owners to review. incorporate/reject PR's then I'd be willing to assist with maintaining the codebase.

In the past, changes to teem codebase have been difficult to get reviewed an uploaded.

A similar issue with vxl existed a few years ago, and once vxl moved to github, the path for PR reviews became much more transparent and the community started to support VXL again.

**Comment by dzenanz** [comment]
@kindlmann [said](https://discourse.itk.org/t/add-a-parallel-compression-method-to-nrrd-and-or-metaimage/696/14?u=dzenanz) that majority of `teem` does not fit well into a library like ITK. And he basically does not have enough time to maintain `teem`.

A migration to GitHub and splitting components into repositories (so NRRD IO gets to be its own repository) would enable direct use of the interesting parts in ITK/VTK/Slicer etc. It would also distribute maintenance burden.

**Comment by hjmjohnson** [comment]
Agreed! and I would be willing to help make that transition.

Hans

**Comment by jcfr** [comment]
I guess the first step would be to defined the scope. There are currently 16 projects referenced at http://teem.sourceforge.net/index.html available within different directories and SVN projects: http://svn.code.sf.net/p/teem/code/

**Comment by kindlmann** [comment]
@dzenanz  I disagree that I don't have time to maintain Teem.  I continue to use it every day for my research.  I agree that its harder to justify spending time helping maintaining how other software projects connect to Teem, or things like NrrdIO that are derived from Teem.

When I originally helped write ITK's support for Nrrd, I wrote scripts (which still work) for extracting those sources from all of Teem that are needed for basic Nrrd IO, and packaging them as a library, called "NrrdIO" (For my work I'm always using all of Teem, so NrrdIO hasn't been updated as it should be).  By design, the API in NrrdIO is exactly the same as that in Teem, albeit with optional name-mangling that matters for things (maybe Slicer?) that may be linking to both NrrdIO and to Teem as a whole.

As part of the "Teem" sourceforge project there is the "Teem" set of C libraries (including "pull", which has some utility in Slicer-related projects for lung CT analysis), and "NrrdIO".  NrrdIO is a useful part of ITK.  Other Teem C libraries (like pull) don't have a fit in ITK, and that's ok.  Slicer embraces all.

@Punzo the chunking mechanism you've implemented is very interesting.  Can you describe how it is actually used by the caller of nrrdRead or nrrdLoad?  I'm wondering if there is analogous information reflected in the NRRD file format or not.

@pieper is sweet to say I'm a busy professor.  Mostly just very distracted.  Also, a dad.  Moving the sourceforge code of Teem onto github is not really the hard part.  The ITK discussion linked above includes my two main requests for help:

(1) complete refresh of all the CMakeLists in Teem (they were written a long time ago when Teem was first being eyed by NAMIC, but haven’t gotten updated to more modern CMake, so there are now weird warnings on Mac that I can't understand), and
(2) getting Teem CTest’d on the same variety of platforms as ITK is tested on. Currently, the only modern CMake stuff for anything in Teem is the way that ITK builds NrrdIO (not all of Teem, and not all of the most recent Teem), and only NrrdIO (not all of Teem) benefits from the testing reported on the ITK dashboard.

Who is going to help?

**Comment by hjmjohnson** [comment]
Gordon, Thanks.  Once it is on GitHub, I can help with modernizing cmake.  I've done that many times before.


Hans

**Comment by Punzo** [comment]
> @Punzo the chunking mechanism you've implemented is very interesting. 

Hi @kindlmann, great, thanks!

> Can you describe how it is actually used by the caller of nrrdRead or nrrdLoad? I'm wondering if there is analogous information reflected in the NRRD file format or not.

I am finalizing the modifications to teem and Slicer. Soon I'll open the PRs and then I'll reply (it will be much easier to comment by pointing directly to the lines).

**Comment by kindlmann** [comment]
I'll start working on moving the sourceforge Teem to my github.
It will take a few days, because I'm slow and plodding, especially when it comes to facing the bright lights of the modern age.

**Comment by hjmjohnson** [comment]
@kindlmann ,

I've gone down this path before, so I'm going to presume to make a few suggestions:
   1)  Make a GitHub organization (i.e. Teem), and then make projects under that rather than using your personal account.
   2) https://help.github.com/articles/source-code-migration-tools/
   3) https://help.github.com/articles/about-github-importer/

THANK YOU.  I am looking forward to assisting with Teem modernization.

Hans

**Comment by dzenanz** [comment]
@kindlmann it looks like I mis-represented what you said elsewhere. Thanks for clarifications!

**Comment by jcfr** [comment]
> can help with modernizing cmake

Ditto. I can also help

Thanks @kindlmann

**Comment by lassoan** [comment]
@kindlmann Have you been able to make any progress in this?

We are only interested in the nrrd reader part of teem, we would like to improve it significantly (add image streaming and random access API, use modern CMake), not limited by backward compatibility, not limited by anyone's availability, we would like to collaborate on this on GitHub, have a good solution within a few months, and use a simple MIT/Apache/BSD license.

To me, it seems that the solution could be one of the followings:
- fork out the teem nrrd reader in a small new project, or
- start from VTK's vtkNrrdReader, improve it, create a small library from the core features that could be used in both VTK and ITK

What do you all think?

**Comment by jcfr** [comment]
Cc: @thewtex @demarle

**Comment by Punzo** [comment]
wrote a very small Lab page regarding this https://www.slicer.org/wiki/Documentation/Labs/NrrdReading_Writing_Optimizations

I have to put aside for the moment further dev on this, but I think we will go on later on. Anyone is welcome to update it, or to continue the dev.

**Comment by jcfr** [comment]
Thanks @Punzo , the page looks great :+1:

**Comment by hjmjohnson** [comment]
> I'll start working on moving the sourceforge Teem to my github.
> It will take a few days, because I'm slow and plodding, especially when it comes to facing the bright lights of the modern age.

@kindlmann Any progress on this. It seems that it is time to update several packages that would like to use teem, but several packages are out of sync with the current svn environment.

**Pull request closed without merging**
